# Generated by Django 4.2.1 on 2023-10-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likepost',
            new_name='Like',
        ),
    ]
