# Generated by Django 4.2.1 on 2023-10-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_like_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follwers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Follwers', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
            ],
        ),
    ]
