# Generated by Django 4.2.1 on 2023-10-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_follwers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follwers',
            new_name='FollwersCount',
        ),
    ]
