# Generated by Django 4.2.1 on 2023-10-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_follwers_follwerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follwerscount',
            old_name='Follwers',
            new_name='follower',
        ),
    ]
