# Generated by Django 4.2.1 on 2023-10-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_followerscount_delete_follwerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileimg2',
            field=models.ImageField(default='/media/blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='/media/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
